version: '3.8'

services:
  postgres:
    image: postgres:15 # You can pin to a specific major version
    container_name: rolltohelp-postgres-dev
    environment:
      POSTGRES_DB: rolltohelp_dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword # Use a more secure password if needed, but this is local-only
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432 (avoids conflict if you have another Postgres on 5432)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data across container restarts
    restart: unless-stopped

volumes:
  postgres_data: # Define the named volume 